
R1_QUESTIONS = [
    { "q": "Identify planets comprising the solar system.", "a": ["Mercury", "Venus", "Earth", "Mars", "Jupiter", "Saturn", "Uranus", "Neptune"] },
    { "q": "Identify the first 8 elements in the periodic table.", "a": ["Hydrogen", "Helium", "Lithium", "Beryllium", "Boron", "Carbon", "Nitrogen", "Oxygen"] },
    { "q": "Identify the colors present in a rainbow.", "a": ["Red", "Orange", "Yellow", "Green", "Blue", "Indigo", "Violet", ""] },
    { "q": "Identify months of the Gregorian calendar.", "a": ["January", "February", "March", "April", "May", "June", "July", "August"] },
    { "q": "Identify the days of the week.", "a": ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday", ""] },
    { "q": "3 peg k baad dost, bhai mera breakup hogya kya karu", "a": ["muth maar","4th peg maar","ro le jitna rona hai","main yahan hoon","explore kar","glow up mode on","breakup celebration","tinder pe bio update kar"]},
    { "q": "ladkia sbse pehli cheez kya notice krti ladko mein", "a": ["confidence", "Bodylanguage", "Dressing sense", "Height","Personality", "Hairstyle", "Sense of Humour", "Scent"] },
    { "q": "Paisa kamane ka sabse easy tarika kya hai?", "a": ["OnlyFans", "Sugar Mommy banana", "Content Creation", "Freelancing", "Selling Online Coaches", "Dropshipping", "Deliver boy", "Black mail"] },
    { "q": "Job interview mein sabse pehle kya dekhte hai?", "a": ["Communication Skills", "Knowledge", "Neat & Clean", "Positive Attitude", "Confidence", "Body Language", "Showing Genuine Interest", "Eye Contact"] },
    { "q": "Nobel Prize award categories", "a": ["Physics", "Chemistry", "Medicine", "Peace", "Literature", "Economics", "", ""] },
    { "q": "Prominent actors in Bollywood", "a": ["ShahRukh", "Aamir", "Salman", "Akshay", "Ranbir", "Hrithik", "Ajay", "Saif"] },
    { "q": "Global fiat currencies", "a": ["Dollar", "Euro", "Yen", "Pound", "Rupee", "Yuan", "Won", "Baht"] },
    { "q": "Mainstream programming languages", "a": ["Python", "JavaScript", "Java", "C++", "Go", "Rust", "Swift", "Ruby"] },
    { "q": "Duniya ke sabse famous scientists kaunsi hain?", "a": ["Albert Einstein", "Isaac Newton", "Marie Curie", "Nikola Tesla", "Charles Darwin", "Stephen Hawking", "Galileo Galilei", "C.V. Raman"] },
    { "q": "Cricket ke sabse important trophies kaunsi hain?", "a": ["ICC World Cup", "T20 World Cup", "IPL Trophy", "Ashes", "Border-Gavaskar Trophy", "Asia Cup", "Champions Trophy", "Ranji Trophy"] },
    { "q": "Teamwork mein sabse important kya hota hai?", "a": ["Trust", "Communication", "Respect", "Collaboration", "Adaptability", "Shared goals", "Conflict resolution", "Support"] },
    { "q": "Presentation ke dauraan sabse pehle kis cheez par dhyaan dena chahiye?", "a": ["Clarity", "Confidence", "Structure", "Audience engagement", "Visuals", "Body language", "Time management", "Voice modulation"] },
    { "q": "Leadership qualities mein sabse zaroori kya hai?", "a": ["Vision", "Decision-making", "Empathy", "Integrity", "Confidence", "Delegation", "Motivation", "Accountability"] },
    { "q": "Networking event mein sabse pehle kya karna chahiye?", "a": ["Introduce yourself", "Smile", "Listen actively", "Ask questions", "Exchange contacts", "Show interest", "Be polite", "Follow up later"] },
    { "q": "Stressful situation mein sabse pehle kya dikhana chahiye?", "a": ["Calmness", "Patience", "Problem-solving", "Positive attitude", "Resilience", "Focus", "Adaptability", "Confidence"] },
    { "q": "Recognized Olympic sports", "a": ["Football", "Basketball", "Tennis", "Swimming", "Boxing", "Hockey", "Cycling", "Wrestling"] },
    { "q": "Commonly consumed fruits", "a": ["Apple", "Banana", "Orange", "Mango", "Grapes", "Pineapple", "Strawberry", "Watermelon"] },
    { "q": "Widely recognized video games", "a": ["Minecraft", "Fortnite", "PUBG", "Call of Duty", "Among Us", "Valorant", "FIFA", "GTA"] },
    { "q": "Major Indian metropolitan areas", "a": ["Mumbai", "Delhi", "Bangalore", "Chennai", "Kolkata", "Hyderabad", "Pune", "Jaipur"] },
    { "q": "Exam ke ek din pehle kya karna chahiye?", "a": ["sojao", "last minute revision kar","Netflix on karlo","jo yaad hai wo likhlo","Bhagwan bharose","Jo hoga dekha jayega","chit bana lo","Confidence ke saath jao,paper bhi tujhe respect karega"] },
    { "q": "Salary aane ke baad sabse pehle kya karna chahiye?", "a": ["biryani order kar","EMI pehle, baaki sab baad mein","Netflix renew kar","Story daal-Rich vibes only", "Maa ko paise de", "Randi chod le", "Shopping mall jao","Savings account khol"] },
    { "q": "Crush ne reply nahi kiya toh kya karna chahiye?", "a": ["tension nhi leni","Message her friend", "meme bhej","Move on", "Game khel", "Patience rakho","Take a chill pill","kal good morning bhej"] },
    { "q": "Weekend pe sabse pehle kya karna chahiye?", "a": ["so jao","Binge watch a Series","GYM","Party karo","chill kar","ghumne jao","Friends se mil","Maa baap ke saath time spend kar"] },
    { "q": "Identify the continents of Earth.", "a": ["Asia", "Africa", "North America", "South America", "Antarctica", "Europe", "Australia", ""] },
    { "q": "Identify the oceans of Earth.", "a": ["Pacific", "Atlantic", "Indian", "Arctic", "Southern", "", "", ""] },
    { "q": "Identify sovereign states located in Europe.", "a": ["France", "Germany", "Italy", "Spain", "UK", "Poland", "Netherlands", "Belgium"] },
    { "q": "Identify states within the Republic of India.", "a": ["Maharashtra", "Uttar Pradesh", "Karnataka", "Tamil Nadu", "West Bengal", "Gujarat", "Rajasthan", "Madhya Pradesh"] },
    { "q": "Identify the largest sovereign states by land area.", "a": ["Russia", "Canada", "USA", "China", "Brazil", "Australia", "India", "Argentina"] },
    { "q": "Boss ne extra kaam de diya toh kya karna chahiye?", "a": ["Say Fuck off","No tension", "Overtime", "LinkedIn khol", "Insta pe story daal-Hardworking employee vibes","Coffee piyo","Promotion hoga", "Boss ko bol–'Sir, main AI hoon kya?"] }
]

R2_QUESTIONS = [
    { "q": "Identify planets comprising the solar system.", "a": ["Mercury", "Venus", "Earth", "Mars", "Jupiter", "Saturn", "Uranus", "Neptune"] },
    { "q": "Identify the first 8 elements in the periodic table.", "a": ["Hydrogen", "Helium", "Lithium", "Beryllium", "Boron", "Carbon", "Nitrogen", "Oxygen"] },
    { "q": "Identify the colors present in a rainbow.", "a": ["Red", "Orange", "Yellow", "Green", "Blue", "Indigo", "Violet", ""] },
    { "q": "Identify months of the Gregorian calendar.", "a": ["January", "February", "March", "April", "May", "June", "July", "August"] },
    { "q": "Identify the days of the week.", "a": ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday", ""] },
    { "q": "3 peg k baad dost, bhai mera breakup hogya kya karu", "a": ["muth maar","4th peg maar","ro le jitna rona hai","main yahan hoon","explore kar","glow up mode on","breakup celebration","tinder pe bio update kar"]},
    { "q": "ladkia sbse pehli cheez kya notice krti ladko mein", "a": ["confidence", "Bodylanguage", "Dressing sense", "Height","Personality", "Hairstyle", "Sense of Humour", "Scent"] },
    { "q": "Paisa kamane ka sabse easy tarika kya hai?", "a": ["OnlyFans", "Sugar Mommy banana", "Content Creation", "Freelancing", "Selling Online Coaches", "Dropshipping", "Deliver boy", "Black mail"] },
    { "q": "Job interview mein sabse pehle kya dekhte hai?", "a": ["Communication Skills", "Knowledge", "Neat & Clean", "Positive Attitude", "Confidence", "Body Language", "Showing Genuine Interest", "Eye Contact"] },
    { "q": "Nobel Prize award categories", "a": ["Physics", "Chemistry", "Medicine", "Peace", "Literature", "Economics", "", ""] },
    { "q": "Prominent actors in Bollywood", "a": ["ShahRukh", "Aamir", "Salman", "Akshay", "Ranbir", "Hrithik", "Ajay", "Saif"] },
    { "q": "Global fiat currencies", "a": ["Dollar", "Euro", "Yen", "Pound", "Rupee", "Yuan", "Won", "Baht"] },
    { "q": "Mainstream programming languages", "a": ["Python", "JavaScript", "Java", "C++", "Go", "Rust", "Swift", "Ruby"] },
    { "q": "Identify the continents of Earth.", "a": ["Asia", "Africa", "North America", "South America", "Antarctica", "Europe", "Australia", ""] },
    { "q": "Identify the oceans of Earth.", "a": ["Pacific", "Atlantic", "Indian", "Arctic", "Southern", "", "", ""] },
    { "q": "Identify sovereign states located in Europe.", "a": ["France", "Germany", "Italy", "Spain", "UK", "Poland", "Netherlands", "Belgium"] },
    { "q": "Identify states within the Republic of India.", "a": ["Maharashtra", "Uttar Pradesh", "Karnataka", "Tamil Nadu", "West Bengal", "Gujarat", "Rajasthan", "Madhya Pradesh"] },
    { "q": "Identify the largest sovereign states by land area.", "a": ["Russia", "Canada", "USA", "China", "Brazil", "Australia", "India", "Argentina"] },
    { "q": "Duniya ke sabse famous scientists kaunsi hain?", "a": ["Albert Einstein", "Isaac Newton", "Marie Curie", "Nikola Tesla", "Charles Darwin", "Stephen Hawking", "Galileo Galilei", "C.V. Raman"] },
    { "q": "Cricket ke sabse important trophies kaunsi hain?", "a": ["ICC World Cup", "T20 World Cup", "IPL Trophy", "Ashes", "Border-Gavaskar Trophy", "Asia Cup", "Champions Trophy", "Ranji Trophy"] },
    { "q": "Teamwork mein sabse important kya hota hai?", "a": ["Trust", "Communication", "Respect", "Collaboration", "Adaptability", "Shared goals", "Conflict resolution", "Support"] },
    { "q": "Presentation ke dauraan sabse pehle kis cheez par dhyaan dena chahiye?", "a": ["Clarity", "Confidence", "Structure", "Audience engagement", "Visuals", "Body language", "Time management", "Voice modulation"] },
    { "q": "Leadership qualities mein sabse zaroori kya hai?", "a": ["Vision", "Decision-making", "Empathy", "Integrity", "Confidence", "Delegation", "Motivation", "Accountability"] },
    { "q": "Networking event mein sabse pehle kya karna chahiye?", "a": ["Introduce yourself", "Smile", "Listen actively", "Ask questions", "Exchange contacts", "Show interest", "Be polite", "Follow up later"] },
    { "q": "Stressful situation mein sabse pehle kya dikhana chahiye?", "a": ["Calmness", "Patience", "Problem-solving", "Positive attitude", "Resilience", "Focus", "Adaptability", "Confidence"] },
    { "q": "Recognized Olympic sports", "a": ["Football", "Basketball", "Tennis", "Swimming", "Boxing", "Hockey", "Cycling", "Wrestling"] },
    { "q": "Commonly consumed fruits", "a": ["Apple", "Banana", "Orange", "Mango", "Grapes", "Pineapple", "Strawberry", "Watermelon"] },
    { "q": "Widely recognized video games", "a": ["Minecraft", "Fortnite", "PUBG", "Call of Duty", "Among Us", "Valorant", "FIFA", "GTA"] },
    { "q": "Major Indian metropolitan areas", "a": ["Mumbai", "Delhi", "Bangalore", "Chennai", "Kolkata", "Hyderabad", "Pune", "Jaipur"] },
    { "q": "Exam ke ek din pehle kya karna chahiye?", "a": ["sojao", "last minute revision kar","Netflix on karlo","jo yaad hai wo likhlo","Bhagwan bharose","Jo hoga dekha jayega","chit bana lo","Confidence ke saath jao,paper bhi tujhe respect karega"] },
    { "q": "Salary aane ke baad sabse pehle kya karna chahiye?", "a": ["biryani order kar","EMI pehle, baaki sab baad mein","Netflix renew kar","Story daal-Rich vibes only", "Maa ko paise de", "Randi chod le", "Shopping mall jao","Savings account khol"] },
    { "q": "Crush ne reply nahi kiya toh kya karna chahiye?", "a": ["tension nhi leni","Message her friend", "meme bhej","Move on", "Game khel", "Patience rakho","Take a chill pill","kal good morning bhej"] },
    { "q": "Weekend pe sabse pehle kya karna chahiye?", "a": ["so jao","Binge watch a Series","GYM","Party karo","chill kar","ghumne jao","Friends se mil","Maa baap ke saath time spend kar"] },
    { "q": "Boss ne extra kaam de diya toh kya karna chahiye?", "a": ["Say Fuck off","No tension", "Overtime", "LinkedIn khol", "Insta pe story daal-Hardworking employee vibes","Coffee piyo","Promotion hoga", "Boss ko bol–'Sir, main AI hoon kya?"] }
]

R3_QUESTIONS = [
    { "q": "Identify planets comprising the solar system.", "a": ["Mercury", "Venus", "Earth", "Mars", "Jupiter", "Saturn", "Uranus", "Neptune"] },
    { "q": "Identify the first 8 elements in the periodic table.", "a": ["Hydrogen", "Helium", "Lithium", "Beryllium", "Boron", "Carbon", "Nitrogen", "Oxygen"] },
    { "q": "Identify the colors present in a rainbow.", "a": ["Red", "Orange", "Yellow", "Green", "Blue", "Indigo", "Violet", ""] },
    { "q": "Identify months of the Gregorian calendar.", "a": ["January", "February", "March", "April", "May", "June", "July", "August"] },
    { "q": "Identify the days of the week.", "a": ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday", ""] },
    { "q": "3 peg k baad dost, bhai mera breakup hogya kya karu", "a": ["muth maar","4th peg maar","ro le jitna rona hai","main yahan hoon","explore kar","glow up mode on","breakup celebration","tinder pe bio update kar"]},
    { "q": "ladkia sbse pehli cheez kya notice krti ladko mein", "a": ["confidence", "Bodylanguage", "Dressing sense", "Height","Personality", "Hairstyle", "Sense of Humour", "Scent"] },
    { "q": "Paisa kamane ka sabse easy tarika kya hai?", "a": ["OnlyFans", "Sugar Mommy banana", "Content Creation", "Freelancing", "Selling Online Coaches", "Dropshipping", "Deliver boy", "Black mail"] },
    { "q": "Job interview mein sabse pehle kya dekhte hai?", "a": ["Communication Skills", "Knowledge", "Neat & Clean", "Positive Attitude", "Confidence", "Body Language", "Showing Genuine Interest", "Eye Contact"] },
    { "q": "Nobel Prize award categories", "a": ["Physics", "Chemistry", "Medicine", "Peace", "Literature", "Economics", "", ""] },
    { "q": "Prominent actors in Bollywood", "a": ["ShahRukh", "Aamir", "Salman", "Akshay", "Ranbir", "Hrithik", "Ajay", "Saif"] },
    { "q": "Global fiat currencies", "a": ["Dollar", "Euro", "Yen", "Pound", "Rupee", "Yuan", "Won", "Baht"] },
    { "q": "Mainstream programming languages", "a": ["Python", "JavaScript", "Java", "C++", "Go", "Rust", "Swift", "Ruby"] },
    { "q": "Duniya ke sabse famous scientists kaunsi hain?", "a": ["Albert Einstein", "Isaac Newton", "Marie Curie", "Nikola Tesla", "Charles Darwin", "Stephen Hawking", "Galileo Galilei", "C.V. Raman"] },
    { "q": "Cricket ke sabse important trophies kaunsi hain?", "a": ["ICC World Cup", "T20 World Cup", "IPL Trophy", "Ashes", "Border-Gavaskar Trophy", "Asia Cup", "Champions Trophy", "Ranji Trophy"] },
    { "q": "Teamwork mein sabse important kya hota hai?", "a": ["Trust", "Communication", "Respect", "Collaboration", "Adaptability", "Shared goals", "Conflict resolution", "Support"] },
    { "q": "Presentation ke dauraan sabse pehle kis cheez par dhyaan dena chahiye?", "a": ["Clarity", "Confidence", "Structure", "Audience engagement", "Visuals", "Body language", "Time management", "Voice modulation"] },
    { "q": "Leadership qualities mein sabse zaroori kya hai?", "a": ["Vision", "Decision-making", "Empathy", "Integrity", "Confidence", "Delegation", "Motivation", "Accountability"] },
    { "q": "Networking event mein sabse pehle kya karna chahiye?", "a": ["Introduce yourself", "Smile", "Listen actively", "Ask questions", "Exchange contacts", "Show interest", "Be polite", "Follow up later"] },
    { "q": "Stressful situation mein sabse pehle kya dikhana chahiye?", "a": ["Calmness", "Patience", "Problem-solving", "Positive attitude", "Resilience", "Focus", "Adaptability", "Confidence"] },
    { "q": "Recognized Olympic sports", "a": ["Football", "Basketball", "Tennis", "Swimming", "Boxing", "Hockey", "Cycling", "Wrestling"] },
    { "q": "Commonly consumed fruits", "a": ["Apple", "Banana", "Orange", "Mango", "Grapes", "Pineapple", "Strawberry", "Watermelon"] },
    { "q": "Widely recognized video games", "a": ["Minecraft", "Fortnite", "PUBG", "Call of Duty", "Among Us", "Valorant", "FIFA", "GTA"] },
    { "q": "Major Indian metropolitan areas", "a": ["Mumbai", "Delhi", "Bangalore", "Chennai", "Kolkata", "Hyderabad", "Pune", "Jaipur"] },
    { "q": "Exam ke ek din pehle kya karna chahiye?", "a": ["sojao", "last minute revision kar","Netflix on karlo","jo yaad hai wo likhlo","Bhagwan bharose","Jo hoga dekha jayega","chit bana lo","Confidence ke saath jao,paper bhi tujhe respect karega"] },
    { "q": "Salary aane ke baad sabse pehle kya karna chahiye?", "a": ["biryani order kar","EMI pehle, baaki sab baad mein","Netflix renew kar","Story daal-Rich vibes only", "Maa ko paise de", "Randi chod le", "Shopping mall jao","Savings account khol"] },
    { "q": "Crush ne reply nahi kiya toh kya karna chahiye?", "a": ["tension nhi leni","Message her friend", "meme bhej","Move on", "Game khel", "Patience rakho","Take a chill pill","kal good morning bhej"] },
    { "q": "Weekend pe sabse pehle kya karna chahiye?", "a": ["so jao","Binge watch a Series","GYM","Party karo","chill kar","ghumne jao","Friends se mil","Maa baap ke saath time spend kar"] },
    { "q": "Identify the continents of Earth.", "a": ["Asia", "Africa", "North America", "South America", "Antarctica", "Europe", "Australia", ""] },
    { "q": "Identify the oceans of Earth.", "a": ["Pacific", "Atlantic", "Indian", "Arctic", "Southern", "", "", ""] },
    { "q": "Identify sovereign states located in Europe.", "a": ["France", "Germany", "Italy", "Spain", "UK", "Poland", "Netherlands", "Belgium"] },
    { "q": "Identify states within the Republic of India.", "a": ["Maharashtra", "Uttar Pradesh", "Karnataka", "Tamil Nadu", "West Bengal", "Gujarat", "Rajasthan", "Madhya Pradesh"] },
    { "q": "Identify the largest sovereign states by land area.", "a": ["Russia", "Canada", "USA", "China", "Brazil", "Australia", "India", "Argentina"] },
    { "q": "Boss ne extra kaam de diya toh kya karna chahiye?", "a": ["Say Fuck off","No tension", "Overtime", "LinkedIn khol", "Insta pe story daal-Hardworking employee vibes","Coffee piyo","Promotion hoga", "Boss ko bol–'Sir, main AI hoon kya?"] }
    ]
